name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - next

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 4

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install system packages required by opam packages
        run: opam depext --update geoip ocurl tls

      - name: Install opam packages
        run: |
          opam pin add websocket-httpaf.~dev https://github.com/anmonteiro/websocket-httpaf.git
          opam pin add websocket-httpaf-lwt.~dev https://github.com/anmonteiro/websocket-httpaf.git
          opam install $(opam show -f depopts: . | sed -e 's/{.*}//g' -e 's/"//g')
          opam install . --deps-only --with-doc --with-test

      - name: Run build
        run: opam exec -- make build
