name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - next

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4
          - 5

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install minimal dependencies
        run: opam install . --deps-only --with-doc --with-test

      - name: Run minimal build
        run: make

      - name: Install depext
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-gnutls-dev libgeoip-dev

      - name: Install optional dependencies for ocaml 4
        run: |
          opam install --best-effort $(opam show -f depopts: . | sed -e 's/{.*}//g' -e 's/"//g' | awk '!($1 ~ /eio/) { print $1 }')
        if: ${{ matrix.ocaml-compiler == 4 }}

      - name: Install optional dependencies for ocaml 5
        run: |
          opam install $(opam show -f depopts: . | sed -e 's/{.*}//g' -e 's/"//g' | awk '{ if ($1 != "js_of_ocaml-eio" && $1 != "geoip") print $1 }')
        if: ${{ matrix.ocaml-compiler != 4 }}

      - name: Run full build
        run: make
